Joshua/futr 955 update workflow docs
mastra-ai/mastra pull request #930
Opened 2024-12-06 16:00 UTC by Joshuafolorunsho

Pizza Workflow Example Documentation
🔄 Replaced web crawler example with relatable pizza ordering workflow
📝 Added clear step-by-step guide for creating workflows
🔗 Improved code examples with proper TypeScript formatting
🎯 Demonstrated key workflow concepts (validation, dependencies, conditions)
📚 Restructured documentation for better readability
🧹 Fixed file paths and code style consistency

2024-12-06 16:18 UTC, Joshuafolorunsho commented
```
@vercel
Vercel – openapi-spec-writer — Deployment has failed
```

Openapi spec writer breaking doesn't have anything to do with docs changes.

2024-12-06 17:36 UTC, Adeniyii requested changes
small errors

2024-12-06 17:36 UTC, Adeniyii commented on docs/src/pages/guide/how-to/03-building-workflows.mdx
> +});
we need a `dependsOn` property here
```suggestion
pizzaWorkflow.config("validatePizzaOrder", {
  dependsOn: [],
  variables: {
    size: { stepId: "trigger", path: "size" },
    toppings: { stepId: "trigger", path: "toppings" },
    specialInstructions: { stepId: "trigger", path: "specialInstructions" },
  },
});
```

2024-12-06 17:36 UTC, Adeniyii commented on docs/src/pages/guide/reference/workflows/config.mdx
> +  ```
here as well

2024-12-06 17:36 UTC, Adeniyii commented on docs/src/pages/guide/reference/workflows/config.mdx
> +  ```
here too

2024-12-06 17:36 UTC, Adeniyii commented on docs/src/pages/guide/reference/workflows/config.mdx
> +  ```
here

2024-12-06 17:36 UTC, Adeniyii commented on docs/src/pages/guide/reference/workflows/workflow.mdx
>        orderStatus: { stepId: "createOrder", path: "status" },
and here

2024-12-07 20:02 UTC, closed without merging

2024-12-08 02:51 UTC, calcsam commented
Thx for closing. Once we fix the APIs, I will re-do the docs.

2024-12-08 06:07 UTC, Joshuafolorunsho commented
> Thx for closing. Once we fix the APIs, I will re-do the docs.

You're welcome.